apiVersion: v1
kind: Service
metadata:
  name: ammara-app
  labels:
    app: ammara-app
spec:
  type: ClusterIP
  selector:
    app: ammara-app
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
