apiVersion: apps/v1
kind: Deployment
metadata:
  name: ammara-app
  labels:
    app: ammara-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ammara-app
  template:
    metadata:
      labels:
        app: ammara-app
    spec:
      containers:
        - name: ammara-app
          image: devopsusr/ammara:v6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: ammara-mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: marriage_app
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ammara-secrets
                  key: mysql-root-password
          readinessProbe:
            httpGet: 
              path: /healthz
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:        
              path: /live
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 2
            failureThreshold: 3                  
          envFrom:
            - secretRef:
                name: ammara-db-secret
